/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import React, { useMemo } from "react";
import { useAccount, useReadContract } from "wagmi";
import { encodeFunctionData } from "viem";
import {
  Transaction,
  TransactionButton,
  TransactionStatus,
  TransactionStatusAction,
  TransactionStatusLabel,
  TransactionToast,
  TransactionToastAction,
  TransactionToastIcon,
  TransactionToastLabel,
} from "@coinbase/onchainkit/transaction";

type BuyDBROWithUsdGasProps = {
  onSuccess?: () => void;
  onError?: (error: unknown) => void;
  className?: string;
  enabled?: boolean;
  amount?: string; // Amount of USDC to swap (will be determined by Swap component)
};

const USDC_DECIMALS = 6;
const USDC_ADDRESS = (process.env.NEXT_PUBLIC_USDC_ADDRESS ||
  "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913") as `0x${string}`;
const PAYMASTER_ADDRESS = process.env
  .NEXT_PUBLIC_PAYMASTER_ADDRESS as `0x${string}` | undefined;

const MIN_THRESHOLD = BigInt(1) * (BigInt(10) ** BigInt(USDC_DECIMALS));
const TOP_UP = BigInt(20) * (BigInt(10) ** BigInt(USDC_DECIMALS));

const erc20Abi = [
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
] as const;

export default function BuyDBROWithUsdGas({
  onSuccess,
  onError,
  className,
  enabled = true,
}: BuyDBROWithUsdGasProps) {
  const { address: userAddress } = useAccount();

  const { data: usdcAllowance } = useReadContract(
    userAddress && PAYMASTER_ADDRESS
      ? {
          address: USDC_ADDRESS,
          abi: erc20Abi,
          functionName: "allowance",
          args: [userAddress as `0x${string}`, PAYMASTER_ADDRESS],
        }
      : undefined,
  );

  // For now, we'll use the Swap component logic but through Transaction
  // This is a placeholder - the actual swap calls would be generated by Swap component
  const finalCalls = useMemo(() => {
    const calls: Array<{ to: `0x${string}`; data: `0x${string}` }> = [];

    const needApprove = PAYMASTER_ADDRESS
      ? typeof usdcAllowance === "bigint"
        ? usdcAllowance < MIN_THRESHOLD
        : true
      : false;

    if (needApprove) {
      const approveUsdcData = encodeFunctionData({
        abi: erc20Abi,
        functionName: "approve",
        args: [PAYMASTER_ADDRESS as `0x${string}`, TOP_UP],
      });
      calls.push({ to: USDC_ADDRESS, data: approveUsdcData });
    }

    // Note: The actual swap call would need to be generated by Swap component
    // For now, this is a placeholder structure
    // In a real implementation, you'd need to get swap data from Swap component
    // or use a swap aggregator/router

    return calls;
  }, [usdcAllowance]);

  const canRender = Boolean(enabled && userAddress && finalCalls.length > 0);

  return (
    <div className={className}>
      {canRender ? (
        <Transaction
          calls={finalCalls as any}
          // @ts-expect-error: 'context' prop may not be typed in current onchainkit version
          context={{ erc20: USDC_ADDRESS }}
          isSponsored
          onSuccess={() => onSuccess && onSuccess()}
          onError={(e) => onError && onError(e)}
        >
          <TransactionButton
            className="usdc-buy-dbro-btn relative w-full bg-primary text-black px-4 py-2 rounded-lg font-mono font-bold text-sm hover:bg-primary-hover/90 disabled:opacity-50 disabled:cursor-not-allowed"
            aria-label="Buy DBRO"
          />
          <TransactionStatus>
            <TransactionStatusAction />
            <TransactionStatusLabel />
          </TransactionStatus>
          <TransactionToast className="mb-2">
            <TransactionToastIcon />
            <TransactionToastLabel />
            <TransactionToastAction />
          </TransactionToast>
        </Transaction>
      ) : (
        <button
          className="w-full bg-primary text-black px-4 py-2 rounded-lg font-bold text-sm opacity-50 cursor-not-allowed"
          disabled
        >
          Buy DBRO
        </button>
      )}
    </div>
  );
}

